<a href="https://colab.research.google.com/github/OJO44/Python-Data-Analysis/blob/main/PandasWeeklyProjectInvestors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Investors flow of funds**

In [22]:
#import the necessary libraries
import pandas as pd
import numpy as ny
import matplotlib.pyplot as plt

In [23]:
#tep 2. Import the dataset from this address.
#Step 3. Assign it to a variable called Investors
data = "https://raw.githubusercontent.com/datasets/investor-flow-of-funds-us/master/data/weekly.csv"
investors = pd.read_csv(data)
investors.head()

,Date,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
0,2012-12-05,-7426,-6060,-1367,-74,5317,4210,1107,-2183
1,2012-12-12,-8783,-7520,-1263,123,1818,1598,219,-6842
2,2012-12-19,-5496,-5470,-26,-73,103,3472,-3369,-5466
3,2012-12-26,-4451,-4076,-375,550,2610,3333,-722,-1291
4,2013-01-02,-11156,-9622,-1533,-158,2383,2103,280,-8931

In [24]:
#Step 4. What is the frequency of the dataset?
investors.describe()

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
count,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000
mean,-161.727273,-1815.931818,1654.227273,684.227273,2452.613636,1931.977273,520.613636,2975.045455
std,4318.401639,3223.717184,1533.770151,670.325983,2729.245012,2574.644536,786.337321,6228.735692
min,-11156.000000,-9622.000000,-1533.000000,-1057.000000,-8193.000000,-8658.000000,-3369.000000,-9040.000000
25%,-1758.500000,-3385.750000,883.250000,249.500000,1524.500000,1089.000000,279.000000,-549.750000
50%,476.000000,-1774.000000,1563.500000,791.500000,2417.000000,1863.500000,668.000000,3948.000000
75%,1916.500000,-22.000000,2561.500000,1072.000000,3610.750000,3235.500000,855.500000,5844.500000
max,14817.000000,7995.000000,6821.000000,2888.000000,9766.000000,7311.000000,2455.000000,27471.000000

In [25]:
#Step 5. Set the column Date as the index.
investors.set_index("Date", inplace=True)
investors.head()

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2012-12-05,-7426,-6060,-1367,-74,5317,4210,1107,-2183
2012-12-12,-8783,-7520,-1263,123,1818,1598,219,-6842
2012-12-19,-5496,-5470,-26,-73,103,3472,-3369,-5466
2012-12-26,-4451,-4076,-375,550,2610,3333,-722,-1291
2013-01-02,-11156,-9622,-1533,-158,2383,2103,280,-8931

In [26]:
#Step 6. What is the type of the index?
#investors.index.dtype
print(type(investors.index))

<class 'pandas.core.indexes.base.Index'>

In [30]:
#Step 7. Set the index to a DatetimeIndex type
investors.index = pd.DatetimeIndex(investors.index)
print(investors.index)

DatetimeIndex(['2012-12-05', '2012-12-12', '2012-12-19', '2012-12-26',
               '2013-01-02', '2013-01-09', '2014-04-02', '2014-04-09',
               '2014-04-16', '2014-04-23', '2014-04-30', '2014-05-07',
               '2014-05-14', '2014-05-21', '2014-05-28', '2014-06-04',
               '2014-06-11', '2014-06-18', '2014-06-25', '2014-07-02',
               '2014-07-09', '2014-07-30', '2014-08-06', '2014-08-13',
               '2014-08-20', '2014-08-27', '2014-09-03', '2014-09-10',
               '2014-11-05', '2014-11-12', '2014-11-19', '2014-11-25',
               '2015-01-07', '2015-01-14', '2015-01-21', '2015-01-28',
               '2015-02-04', '2015-02-11', '2015-03-04', '2015-03-11',
               '2015-03-18', '2015-03-25', '2015-04-01', '2015-04-08'],
              dtype='datetime64[ns]', name='Date', freq=None)

In [32]:
#Step 8. Change the frequency to monthly, sum the values and assign it to monthly.
monthly= investors.resample("M").sum()
print(monthly)

            Total Equity  Domestic Equity  World Equity  Hybrid  Total Bond  \
Date
2012-12-31        -26156           -23126         -3031     526        9848
2013-01-31          3661            -1627          5288    2730       12149
2013-02-28             0                0             0       0           0
2013-03-31             0                0             0       0           0
2013-04-30             0                0             0       0           0
2013-05-31             0                0             0       0           0
2013-06-30             0                0             0       0           0
2013-07-31             0                0             0       0           0
2013-08-31             0                0             0       0           0
2013-09-30             0                0             0       0           0
2013-10-31             0                0             0       0           0
2013-11-30             0                0             0       0           0
2013-12-31             0                0             0       0           0
2014-01-31             0                0             0       0           0
2014-02-28             0                0             0       0           0
2014-03-31             0                0             0       0           0
2014-04-30         10842             1048          9794    4931        8493
2014-05-31         -2203            -8720          6518    3172       13767
2014-06-30          2319            -6546          8865    4588        9715
2014-07-31         -7051           -11128          4078    2666        7506
2014-08-31          1943            -5508          7452    1885        1897
2014-09-30         -2767            -6596          3829    1599        3984
2014-10-31             0                0             0       0           0
2014-11-30         -2753            -7239          4485     729       14528
2014-12-31             0                0             0       0           0
2015-01-31          3471            -1164          4635    1729        7368
2015-02-28          5508             3509          1999    1752        9099
2015-03-31          5691            -8176         13867    2829        9138
2015-04-30           379            -4628          5007     970         423

            Taxable Bond  Municipal Bond  Total
Date
2012-12-31         12613           -2765 -15782
2013-01-31          9414            2735  18540
2013-02-28             0               0      0
2013-03-31             0               0      0
2013-04-30             0               0      0
2013-05-31             0               0      0
2013-06-30             0               0      0
2013-07-31             0               0      0
2013-08-31             0               0      0
2013-09-30             0               0      0
2013-10-31             0               0      0
2013-11-30             0               0      0
2013-12-31             0               0      0
2014-01-31             0               0      0
2014-02-28             0               0      0
2014-03-31             0               0      0
2014-04-30          7193            1300  24267
2014-05-31         10192            3576  14736
2014-06-30          7551            2163  16621
2014-07-31          7026             481   3122
2014-08-31         -1013            2910   5723
2014-09-30          2479            1504   2816
2014-10-31             0               0      0
2014-11-30         11566            2962  12502
2014-12-31             0               0      0
2015-01-31          2762            4606  12569
2015-02-28          7443            1656  16359
2015-03-31          7267            1870  17657
2015-04-30           514             -91   1772

In [33]:
#Step 9. You will notice that it filled the dataFrame with months that don't have any data with NaN. Let's drop these rows.
monthly = monthly.dropna()
print(monthly)

            Total Equity  Domestic Equity  World Equity  Hybrid  Total Bond  \
Date
2012-12-31        -26156           -23126         -3031     526        9848
2013-01-31          3661            -1627          5288    2730       12149
2013-02-28             0                0             0       0           0
2013-03-31             0                0             0       0           0
2013-04-30             0                0             0       0           0
2013-05-31             0                0             0       0           0
2013-06-30             0                0             0       0           0
2013-07-31             0                0             0       0           0
2013-08-31             0                0             0       0           0
2013-09-30             0                0             0       0           0
2013-10-31             0                0             0       0           0
2013-11-30             0                0             0       0           0
2013-12-31             0                0             0       0           0
2014-01-31             0                0             0       0           0
2014-02-28             0                0             0       0           0
2014-03-31             0                0             0       0           0
2014-04-30         10842             1048          9794    4931        8493
2014-05-31         -2203            -8720          6518    3172       13767
2014-06-30          2319            -6546          8865    4588        9715
2014-07-31         -7051           -11128          4078    2666        7506
2014-08-31          1943            -5508          7452    1885        1897
2014-09-30         -2767            -6596          3829    1599        3984
2014-10-31             0                0             0       0           0
2014-11-30         -2753            -7239          4485     729       14528
2014-12-31             0                0             0       0           0
2015-01-31          3471            -1164          4635    1729        7368
2015-02-28          5508             3509          1999    1752        9099
2015-03-31          5691            -8176         13867    2829        9138
2015-04-30           379            -4628          5007     970         423

            Taxable Bond  Municipal Bond  Total
Date
2012-12-31         12613           -2765 -15782
2013-01-31          9414            2735  18540
2013-02-28             0               0      0
2013-03-31             0               0      0
2013-04-30             0               0      0
2013-05-31             0               0      0
2013-06-30             0               0      0
2013-07-31             0               0      0
2013-08-31             0               0      0
2013-09-30             0               0      0
2013-10-31             0               0      0
2013-11-30             0               0      0
2013-12-31             0               0      0
2014-01-31             0               0      0
2014-02-28             0               0      0
2014-03-31             0               0      0
2014-04-30          7193            1300  24267
2014-05-31         10192            3576  14736
2014-06-30          7551            2163  16621
2014-07-31          7026             481   3122
2014-08-31         -1013            2910   5723
2014-09-30          2479            1504   2816
2014-10-31             0               0      0
2014-11-30         11566            2962  12502
2014-12-31             0               0      0
2015-01-31          2762            4606  12569
2015-02-28          7443            1656  16359
2015-03-31          7267            1870  17657
2015-04-30           514             -91   1772

In [34]:
#Step 10. Good, now we have the monthly data. Now change the frequency to year.
yearly = monthly.resample('Y').sum()
print(yearly)

            Total Equity  Domestic Equity  World Equity  Hybrid  Total Bond  \
Date
2012-12-31        -26156           -23126         -3031     526        9848
2013-12-31          3661            -1627          5288    2730       12149
2014-12-31           330           -44689         45021   19570       59890
2015-12-31         15049           -10459         25508    7280       26028

            Taxable Bond  Municipal Bond  Total
Date
2012-12-31         12613           -2765 -15782
2013-12-31          9414            2735  18540
2014-12-31         44994           14896  79787
2015-12-31         17986            8041  48357