<a href="https://colab.research.google.com/github/OJO44/Python-Data-Analysis/blob/main/PandasDailyPractice3MergeAutoMPG.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Auto_MPG Cars**

In [ ]:
#Step 1. Import the necessary libraries
import pandas as pd
import numpy as np

In [ ]:
#Step 2. Import the first dataset cars1 and cars2.
#Step 3. Assign each to a variable called cars1 and cars2
cars1 = "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv"
cars2= "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv"
cars1= pd.read_csv(cars1)
cars2= pd.read_csv(cars2)
cars1.head(10)
#cars2.head(10)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN
5,15.0,8,429,198,4341,10.0,70,1,ford galaxie 500,NaN,NaN,NaN,NaN,NaN
6,14.0,8,454,220,4354,9.0,70,1,chevrolet impala,NaN,NaN,NaN,NaN,NaN
7,14.0,8,440,215,4312,8.5,70,1,plymouth fury iii,NaN,NaN,NaN,NaN,NaN
8,14.0,8,455,225,4425,10.0,70,1,pontiac catalina,NaN,NaN,NaN,NaN,NaN
9,15.0,8,390,190,3850,8.5,70,1,amc ambassador dpl,NaN,NaN,NaN,NaN,NaN

In [ ]:
cars2.head(10)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,33.0,4,91,53,1795,17.4,76,3,honda civic
1,20.0,6,225,100,3651,17.7,76,1,dodge aspen se
2,18.0,6,250,78,3574,21.0,76,1,ford granada ghia
3,18.5,6,250,110,3645,16.2,76,1,pontiac ventura sj
4,17.5,6,258,95,3193,17.8,76,1,amc pacer d/l
5,29.5,4,97,71,1825,12.2,76,2,volkswagen rabbit
6,32.0,4,85,70,1990,17.0,76,3,datsun b-210
7,28.0,4,97,75,2155,16.4,76,3,toyota corolla
8,26.5,4,140,72,2565,13.6,76,1,ford pinto
9,20.0,4,130,102,3150,15.7,76,2,volvo 245

In [ ]:
#Step 4. Oops, it seems our first dataset has some unnamed blank columns, fix cars1
cars1=cars1.dropna(axis=1, how="all") #this remove columns with NaN values from the DataFrame car1
cars1.head(10)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
5,15.0,8,429,198,4341,10.0,70,1,ford galaxie 500
6,14.0,8,454,220,4354,9.0,70,1,chevrolet impala
7,14.0,8,440,215,4312,8.5,70,1,plymouth fury iii
8,14.0,8,455,225,4425,10.0,70,1,pontiac catalina
9,15.0,8,390,190,3850,8.5,70,1,amc ambassador dpl

In [ ]:
#Step 5. What is the number of observations in each dataset?
observation_cars1= cars1.shape[0]
display(observation_cars1)

198

In [ ]:
observation_cars2= cars2.shape[0]
display(observation_cars2)

200

In [ ]:
#Step 6. Join cars1 and cars2 into a single DataFrame called cars
cars =pd.concat([cars1,cars2])
cars.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Step 7. Oops, there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.
owners = np.random.randint(1500,73001, size = len(cars))
print(owners)

[70211 68796 42033 23190 22339 24136 61984 56686  2757 50341  4747 21611
  3568 51368 22153 11258 54532 19359 10656  2000 28588 56764 43070 17207
 29325 48756 47900  7307  6677 40225 72310  6568 36419 46644 45325 15973
 38934 47574 38728 40375 22141 10235 47044 42186 71479  7534 26782 26002
 56836 46216 39295 23259 39657 53569 11120 11329 67445 49276 30405 57060
 23829 65258 22100 71288 47905  6898 61994 51447 53324 70620 20212 36137
 24420 10997 66817 68106 66569 44564 53230 22821 32872 20198 66256 52681
 71454 72272 28089 14860 43186  4580 26300  5754 54958 53024 32368 26375
 23243 47913 64041 37771 23783 39821 43351 34723 22965 25323  6438 62479
 22350 57918 65943 33396 45409 16834 43190 29896 16556  2243 17564 56724
  6476 43837 46812 53131  3943 71822 14073 29750 71630  3399 47975  8170
 43042 32748  1756 37943 61064 60060 63871 52005 53825 25551 27024 19259
 67076  6080  2292 66224 13348 48030 70971 23290 72315 46309 67431 68466
 43519 15337 68186 69763 45479 55598 59357 34096 30628  4660 23008 57212
 50659 26297  2871 49974 69556 46751  8196 56569 19531  5211 46574 62434
 56425 26824 64465 15688  6516 61072 65613 18730 34484 67421 52597 22850
 43565 33045 55201 17122 50878 61754 27871 66507 70865 66465 67871  9462
 44895 33484 42047 46247 19442 62579 25796 41767 31760  7445 67230 64568
 13628 61892 54449 11269 24261 49128 38753  9537 54662 69501 54003 23521
 71701 41003 51429  3360 17374 66118 56579 52398 11912 14962 65282 27403
 13133 58293 60908 71498 28912 23169 35772 21900 44499 34967 64441 66526
 21273 69120 20195 53508 66711 47665 17247 36168 25772 43534 59692 59119
 29791 32288 68545 11232 27322 66916 36193 24718 47752 34593 13833 10425
 24581 43183 61013  1878 10892 55377 14119 14076 72996 52777 23010  8320
 44070 58159 12006  6477 28869 28605 59400 12493  5702 66959 40826 39648
  5134 58292 44029 47147 34751 13728 38737 40957 28863 23466 60129 22318
 23929 11103 60499 67761 12153 31086 12022 25031 61939 68734 50455 37646
 47041 51605 45728 41555 60019 17810 24171 24111 46682 66907 20078 16468
 57234 56954 55604  7632 68876 48108 66331 29246 45225  4875 32123 15926
 29992 18502 20920 19821 48236 57969  9767  8930 55554 18380 62983 26839
 71891 17335 30939 13235 46818 72536 30878 64110 14763 29469 25126 64542
 16821 55195  3416 72892  9211  6400 28999 44720 10285 47592 48398 63882
 10505 41968 22729 49260 41863 14408 39655 14731 50507 60473 68168 13297
 49620 25721]

In [ ]:
#Step 8. Add the column owners to cars
cars["owners"] = owners
cars.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,owners
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN,70211
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN,68796
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN,42033
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN,23190
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN,22339

**Fictitious Names**