<a href="https://colab.research.google.com/github/OJO44/Python-Data-Analysis/blob/main/PythonDailyPractice4USBabyNames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**US Baby Names**

In [8]:
#Step1 Import the necessary Libraries
import pandas as pd
import numpy as np

In [15]:
#Step 2. Import the dataset from this address.
#Step 3. Assign it to a variable called baby_names.
#Step 4. See the first 10 entries
data = "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv"
baby_names = pd.read_csv(data)
baby_names.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

In [16]:
#Step 5. Delete the column 'Unnamed: 0' and 'Id'
baby_names.drop(columns= ["Unnamed: 0", "Id"])

            Name  Year Gender State  Count
0           Emma  2004      F    AK     62
1        Madison  2004      F    AK     48
2         Hannah  2004      F    AK     46
3          Grace  2004      F    AK     44
4          Emily  2004      F    AK     41
...          ...   ...    ...   ...    ...
1016390     Seth  2014      M    WY      5
1016391  Spencer  2014      M    WY      5
1016392     Tyce  2014      M    WY      5
1016393   Victor  2014      M    WY      5
1016394   Waylon  2014      M    WY      5

[1016395 rows x 5 columns]

In [12]:
#Step 6. Is there more male or female names in the dataset?
gender_counts = baby_names['Gender'].value_counts()
print(gender_counts)
#No there are more females than males

Gender
F    558846
M    457549
Name: count, dtype: int64

In [18]:
#Step 7. Group the dataset by name and assign to names
names= baby_names.groupby("Name")
print(names)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7e809a9abe20>

In [21]:
#Step 8. How many different names exist in the dataset?
uniqe_names= baby_names["Name"].nunique()
print(uniqe_names)

17632

In [22]:
#Step 9. What is the name with most occurrences?
name_with_most_occurence = baby_names["Name"].value_counts().idxmax()
print(name_with_most_occurence)

Riley

In [23]:
#Step 10. How many different names have the least occurrences?
least_occurence_names = baby_names["Name"].value_counts().min().sum()
print(least_occurence_names)

1

In [27]:
#Step 11. What is the median name occurrence?
median_name_occurence = baby_names["Name"].value_counts().median()
print(median_name_occurence)

8.0

In [28]:
#Step 12. What is the standard deviation of names?
name_std = baby_names["Name"].value_counts().std()
print(name_std)

122.0299635081389

In [29]:
#Step 13. Get a summary with the mean, min, max, std and quartiles
names_summary = baby_names['Name'].value_counts().describe()
print(names_summary)

count    17632.000000
mean        57.644907
std        122.029964
min          1.000000
25%          2.000000
50%          8.000000
75%         39.000000
max       1112.000000
Name: count, dtype: float64